[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flash_lend = "7niFkVN9AF2vUnHemUyFAzikAfB2LYmKQvreTFiwKRQ8"  # Changed from "flashloan"

[programs.testnet]
flash_lend = "7niFkVN9AF2vUnHemUyFAzikAfB2LYmKQvreTFiwKRQ8"  # Changed from "flashloan"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
url = "https://api.testnet.sonic.game"
wallet = "/home/techsteck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"